try {
    console.log('try');

    console.log('end try');
} catch(err) {
    console.log('error');
}